apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: kubernetes-calc
          image: s222520626/kubernetes-calc-repo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calc
  ports:
    - port: 4026
      targetPort: 8080
  type: LoadBalancer
