apiVersion: v1
kind: Secret
metadata:
  name: database-username
type: Opaque
stringData:
  user: database-user
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password
type: Opaque
stringData:
  password: a#D5?4vN0@mUnfd&5
